# Generated by Django 5.0.7 on 2024-07-20 19:02

import netbox_floorplan.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0008_floorplanimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanimage',
            name='file',
            field=models.FileField(blank=True, upload_to=netbox_floorplan.utils.file_upload),
        ),
    ]
