# Generated by Django 5.0.7 on 2024-07-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0009_floorplanimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanimage',
            name='external_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
