# Generated by Django 5.0.7 on 2024-07-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0010_floorplanimage_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplanimage',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
