# Generated by Django 5.0.7 on 2024-07-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_floorplan', '0011_floorplanimage_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ('site', 'location', 'assigned_image', 'width', 'height', 'measurement_unit')},
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='background_image',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='assigned_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='netbox_floorplan.floorplanimage'),
        ),
    ]
